{
    'name': 'ZZ',
    'depends': ['website', 'base', 'web', 'mail', 'base_setup'],
    'description': """
     odoo基础测试模块,集成报表打印预览功能
     """,
    'category': 'ZZ',
    'author': '张众',
    'data': [
        'security/main_model_security.xml',
        'security/ir.model.access.csv',
        'data/teachers.xml',
        'data/peoples.xml',
        'data/teacher.yml',
        'data/zz.peoples.csv',
        'data/zz.province.csv',
        'data/zz.city.csv',
        'data/zz.town.csv',
        'views/assets.xml',
        'views/front_layout.xml',
        'views/front_login_signup.xml',
        'views/front_page1.xml',
        'views/front_page2.xml',
        'views/back_views1.xml',
        'views/back_views2.xml',
        'views/back_views3.xml',
        'views/back_zsettings_views.xml',
        'views/back_views_menu_action.xml',
        'report/report_template.xml',
        'report/report_action.xml',
    ],
    'qweb': ["static/src/xml/*.xml", ],
    'installable': True,
    'auto_install': False,
    'application': True,
    # 'post_init_hook': 'post_init_hook',
}
